force-app/main/default/objects/Master_Resume__c/Master_Resume__c.object-meta.xml
<CustomObject>
    <label>Master Resume</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Resume__c/fields/Credential_Id__c.field-meta.xml
<CustomField>
    <fullName>Credential_Id__c</fullName>
    <label>Credential ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Resume__c/fields/No_Expiry__c.field-meta.xml
<CustomField>
    <fullName>No_Expiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Expiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Master_Resume__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Resumes</relationshipLabel>
    <relationshipName>Master_Resumes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Resume__c/recordTypes/Certification.recordType-meta.xml
<RecordType>
    <fullName>Certification</fullName>
    <active>true</active>
    <label>Certification</label>
</RecordType>

force-app/main/default/objects/Master_Resume__c/recordTypes/Summary.recordType-meta.xml
<RecordType>
    <fullName>Summary</fullName>
    <active>true</active>
    <label>Summary</label>
</RecordType>

force-app/main/default/classes/Resume.cls
public without sharing class Resume {
    @AuraEnabled
    public String displayName;
    @AuraEnabled
    public String title;
    @AuraEnabled
    public String email;
    @AuraEnabled
    public String phonenumber;
    @AuraEnabled
    public String location;
    @AuraEnabled
    public String summary;
    @AuraEnabled
    public List<Master_Resume__c> skills;
    @AuraEnabled
    public List<Master_Resume__c> awards;
    @AuraEnabled
    public List<Certification> certifications;    
    @AuraEnabled
    public List<Master_Resume__c> licences;
    @AuraEnabled
    public List<Master_Resume__c> recognitions;
    @AuraEnabled
    public List<Master_Resume__c> experiences;
    @AuraEnabled
    public List<Master_Resume__c> educations;
    @AuraEnabled
    public List<Master_Resume__c> references;

    public class Certification{
        @AuraEnabled
        public String certId;
        @AuraEnabled
        public String certName;
        @AuraEnabled
        public String orgName;
        @AuraEnabled
        public Date startDate;
        @AuraEnabled
        public Date endDate;
        @AuraEnabled
        public Boolean noExpiry;
        @AuraEnabled
        public String cerdentialId;
        @AuraEnabled
        public String certImageURL;
        
        public Certification(Master_Resume__c mr){
            this.certId = mr.Id;
            this.certName = mr.Name;
            this.orgName = mr.Organization__r.Name;
            this.startDate = mr.Start_Date__c;
            this.endDate = mr.End_Date__c;
            this.noExpiry = mr.No_Expiry__c;
            this.cerdentialId = mr.Credential_Id__c;
        }
    }
}